### ISSUE TITLE
Rewrite Entity API

### ISSUE THREAD

**Issue by WeeSkilz** [PocketServerMP/PocketServer#43] opened 2015-12-26 23:11 UTC
hi, I'm a message

**Comment by Fireflies** [comment] 2015-12-27 00:01
:+1:

**Comment by nickrobson** [comment] 2015-12-27 00:08
No description is a good description. :+1:

**Comment by Serializator** [comment] 2015-12-27 20:24
:+1:

**Comment by nickrobson** [comment] 2015-12-28 00:21
I believe this was fixed by #46

**Comment by WeeSkilz** [comment] 2015-12-28 00:23
@nickrobson the issue runs deeper than that.

**Comment by nickrobson** [comment] 2015-12-28 00:50
@WeeSkilz would you mind telling me what the issue is then? the lack of a message in the issue report doesn't really help :|

**Comment by Serializator** [comment] 2015-12-28 00:58
@nickrobson We're already working on it, so the message isn't a problem.

**Closed** 2015-12-30 00:38 UTC
